-- MySQL Script generated by MySQL Workbench
-- 11/25/16 09:41:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `course` VARCHAR(45) NOT NULL COMMENT '',
  `section` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faculty` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `department` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `position` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_number` VARCHAR(45) NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  `lastname` VARCHAR(45) NOT NULL COMMENT '',
  `firstname` VARCHAR(45) NOT NULL COMMENT '',
  `middle_initial` VARCHAR(45) NOT NULL COMMENT '',
  `gender` ENUM('Male', 'Female') NOT NULL COMMENT '',
  `age` INT(2) NOT NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `contact_number` VARCHAR(11) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `faculty_id` INT NOT NULL COMMENT '',
  `staff_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `student_id`, `faculty_id`, `staff_id`)  COMMENT '',
  INDEX `fk_patient_student1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_patient_faculty1_idx` (`faculty_id` ASC)  COMMENT '',
  INDEX `fk_patient_staff1_idx` (`staff_id` ASC)  COMMENT '',
  CONSTRAINT `fk_patient_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `mydb`.`faculty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personnel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `email_address` VARCHAR(100) NOT NULL COMMENT '',
  `password` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`complaint` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `complaint` VARCHAR(100) NOT NULL COMMENT '',
  `date_time` TIMESTAMP(1) NOT NULL COMMENT '',
  `patient_id` INT NOT NULL COMMENT '',
  `patient_student_id` INT NULL COMMENT '',
  `patient_faculty_id` INT NULL COMMENT '',
  `patient_staff_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_complaint_patient1_idx` (`patient_id` ASC, `patient_student_id` ASC, `patient_faculty_id` ASC, `patient_staff_id` ASC)  COMMENT '',
  CONSTRAINT `fk_complaint_patient1`
    FOREIGN KEY (`patient_id` , `patient_student_id` , `patient_faculty_id` , `patient_staff_id`)
    REFERENCES `mydb`.`patient` (`id` , `student_id` , `faculty_id` , `staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medicine` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `medicine_given` VARCHAR(100) NOT NULL COMMENT '',
  `medicine_quantity` INT NOT NULL COMMENT '',
  `complaint_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `complaint_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_medicine_complaint1_idx` (`complaint_id` ASC)  COMMENT '',
  CONSTRAINT `fk_medicine_complaint1`
    FOREIGN KEY (`complaint_id`)
    REFERENCES `mydb`.`complaint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
